Add model metadata
sony/mct_quantizers pull request #86
Opened 2024-04-04 14:05 UTC by elad-c

## Pull Request Description:
Add API for adding a metadata dictionary to Keras\Pytorch\ONNX models

## Checklist before requesting a review:
- [ ] I set the appropriate labels on the pull request.
- [ ] I have added/updated the release note draft (if necessary).
- [ ] I have updated the documentation to reflect my changes (if necessary).
- [ ] All function and files are well documented. 
- [ ] All function and classes have type hints.
- [ ] There is a licenses in all file.
- [ ] The function and variable names are informative. 
- [ ] I have checked for code duplications.
- [ ] I have added new unittest (if necessary).

2024-04-07 10:17 UTC, ofirgo approved these changes
Some minor comments.
Additionally - do we want to figure out how to add this to the backward/forward compatibility tests?

2024-04-07 10:17 UTC, ofirgo commented on mct_quantizers/common/metadata.py
> +import mct_quantizers
why do we need to import mct_quantizers? if it's only for the version maybe import the version directly if it's possible? (because it's just weird to import mctq inside mctq)

2024-04-07 10:17 UTC, ofirgo commented on mct_quantizers/common/metadata.py
> +    if not isinstance(metadata, dict):
Please use capital letters at the beginning of sentences

2024-04-07 10:17 UTC, ofirgo commented on mct_quantizers/common/metadata.py
> +        Logger.error('metadata dictionary should only have string, integer or float values.')
just to understand, why do we have this restriction?

2024-04-07 10:17 UTC, ofirgo commented on mct_quantizers/keras/load_model.py
> +        # Extract metadata is exists
typo (is --> if)

2024-04-07 10:17 UTC, ofirgo commented on mct_quantizers/keras/load_model.py
> +                Logger.warning('Found more than 1 MetadataLayer layers in model.')
add "Loading the metadata from the first layer only" or something like that

2024-04-07 10:17 UTC, ofirgo commented on mct_quantizers/keras/metadata.py
> +        model.metadata = model.metadata_layer.metadata
is this necessary? why the redundancy?
how does that even work? how does the model have "metadata" attribute?

2024-04-07 15:51 UTC, Chizkiyahu commented on mct_quantizers/common/metadata.py
> +        metadata[MCTQ_VERSION] = mct_quantizers.__version__
in the example model that I got the value was '__version__'
please check that this kine works

2024-04-07 15:51 UTC, Chizkiyahu commented on tests/keras_tests/test_keras_load_model.py
> +        _, tmp_h5_file = tempfile.mkstemp('.h5')
please add also .keras test

2024-04-07 16:00 UTC, reuvenperetz requested changes

2024-04-07 16:00 UTC, reuvenperetz commented on mct_quantizers/pytorch/metadata.py
> +            Logger.critical('Installing pytorch is mandatory '
Installing onnx...

2024-04-07 16:00 UTC, reuvenperetz commented on mct_quantizers/pytorch/metadata.py
> +
Why no example usage for onnx?

2024-04-07 16:00 UTC, reuvenperetz commented on mct_quantizers/pytorch/metadata.py
> +            metadata[FRAMEWORK_VERSION] = torch.__version__
Why do we need torch version here?

2024-04-08 08:03 UTC, reuvenperetz approved these changes

2024-04-08 08:04 UTC, merged